import { createHash, randomBytes } from "node:crypto";
import { createServer } from "node:http";
import type { AddressInfo } from "node:net";
import { describe, expect, it, beforeAll, afterAll, vi } from "vitest";
import { EmbeddingsClient } from "../../src/clients/embeddings.js";
import { ReadonlyQdrantClient } from "../../src/clients/qdrant-readonly.js";
import { MemoryRetriever } from "../../src/retrieval/search.js";
import { AdminQdrantClient, type AdminPoint } from "../../src/admin/qdrant-admin.js";
import { applyHermesImport, planHermesImport, type ImportOptions } from "../../src/admin/import-hermes.js";
import type { RetrievalConfig } from "../../src/types.js";
import { startEmbeddingStub } from "./embedding-stub.js";

const SOURCE_PREFIX = "pi_qdrant_memory_it_source_";
const DESTINATION_PREFIX = "pi_qdrant_memory_it_destination_";
const GENERATED_SUFFIX = /^[a-f0-9]{32}$/;
const generatedCollections = new Set<string>();

function generatedCollection(prefix: typeof SOURCE_PREFIX | typeof DESTINATION_PREFIX): string {
  const name = `${prefix}${randomBytes(16).toString("hex")}`;
  generatedCollections.add(name);
  return name;
}

function assertGeneratedCollection(name: string): void {
  const prefix = name.startsWith(SOURCE_PREFIX)
    ? SOURCE_PREFIX
    : name.startsWith(DESTINATION_PREFIX)
      ? DESTINATION_PREFIX
      : undefined;
  if (
    prefix === undefined ||
    !GENERATED_SUFFIX.test(name.slice(prefix.length)) ||
    !generatedCollections.has(name)
  ) {
    throw new Error("refusing to operate on a collection not generated by this test process");
  }
}

function delay(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function closeWithin(close: () => Promise<void>, timeoutMs = 1_000): Promise<void> {
  let timer: NodeJS.Timeout | undefined;
  try {
    await Promise.race([
      close(),
      new Promise<never>((_resolve, reject) => {
        timer = setTimeout(() => reject(new Error("test HTTP server close timed out")), timeoutMs);
      }),
    ]);
  } finally {
    if (timer !== undefined) clearTimeout(timer);
  }
}

function expectedEmbedding(model: string, input: string): number[] {
  const digest = createHash("sha256").update(model + input).digest();
  const vector = Array.from(digest.subarray(0, 4), byte => (byte - 127.5) / 127.5);
  const norm = Math.hypot(...vector) || 1;
  return vector.map(value => value / norm);
}

describe("deterministic embedding stub", () => {
  it("binds loopback, records immutable validated snapshots, and returns a normalized dimension-4 embedding", async () => {
    const stub = await startEmbeddingStub();
    try {
      const endpoint = new URL(stub.baseUrl);
      expect(endpoint.hostname).toBe("127.0.0.1");
      expect(Number(endpoint.port)).toBeGreaterThan(0);

      const response = await fetch(`${stub.baseUrl}/embeddings`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ model: "integration-model", input: "search_query: alpha" }),
      });
      expect(response.status).toBe(200);
      const body = await response.json() as {
        object: string;
        model: string;
        data: Array<{ object: string; index: number; embedding: number[] }>;
      };
      const expected = expectedEmbedding("integration-model", "search_query: alpha");
      expect(body).toMatchObject({
        object: "list",
        model: "integration-model",
        data: [{ object: "embedding", index: 0 }],
      });
      expect(body.data[0]?.embedding).toEqual(expected);
      expect(body.data[0]?.embedding).toHaveLength(4);
      expect(body.data[0]?.embedding.every(Number.isFinite)).toBe(true);
      expect(Math.hypot(...(body.data[0]?.embedding ?? []))).toBeCloseTo(1, 12);

      expect(stub.requests).toEqual([{
        method: "POST",
        path: "/v1/embeddings",
        contentType: "application/json",
        model: "integration-model",
        input: "search_query: alpha",
      }]);
      expect(Object.isFrozen(stub.requests[0])).toBe(true);
    } finally {
      await closeWithin(stub.close);
      await closeWithin(stub.close);
    }
  });

  it("returns fixed 4xx responses for non-POST, wrong paths/content types, and malformed bodies", async () => {
    const stub = await startEmbeddingStub();
    try {
      const cases: Array<{ url: string; init: RequestInit; status: number; code: string }> = [
        { url: `${stub.baseUrl}/embeddings`, init: { method: "GET" }, status: 405, code: "method_not_allowed" },
        { url: `${stub.baseUrl}/unknown`, init: { method: "POST" }, status: 404, code: "not_found" },
        {
          url: `${stub.baseUrl}/embeddings`,
          init: { method: "POST", headers: { "content-type": "text/plain" }, body: "{}" },
          status: 415,
          code: "unsupported_media_type",
        },
        {
          url: `${stub.baseUrl}/embeddings`,
          init: { method: "POST", headers: { "content-type": "application/json" }, body: "{" },
          status: 400,
          code: "invalid_request",
        },
        {
          url: `${stub.baseUrl}/embeddings`,
          init: { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ model: "", input: [] }) },
          status: 400,
          code: "invalid_request",
        },
      ];
      for (const testCase of cases) {
        const response = await fetch(testCase.url, testCase.init);
        expect(response.status).toBe(testCase.status);
        expect(await response.json()).toEqual({ error: { code: testCase.code } });
      }
      expect(stub.requests).toEqual([]);
    } finally {
      await closeWithin(stub.close);
    }
  });
});

describe("bounded test-local Qdrant transport", () => {
  it("aborts a stalled loopback response and leaves its server fully closed", async () => {
    const server = createServer((_request, response) => {
      response.writeHead(200, { "content-type": "application/json", "content-length": "128" });
      response.flushHeaders();
      // Deliberately leave the response body incomplete after sending headers.
    });
    await new Promise<void>((resolve, reject) => {
      server.once("error", reject);
      server.listen(0, "127.0.0.1", resolve);
    });
    const address = server.address() as AddressInfo;
    let closePromise: Promise<void> | undefined;
    const startClose = (): Promise<void> => {
      closePromise ??= new Promise<void>((resolve, reject) => {
        server.close(error => error === undefined ? resolve() : reject(error));
      });
      return closePromise;
    };
    const forcedCleanup = setTimeout(() => server.closeAllConnections(), 750);

    try {
      const startedAt = Date.now();
      await expect(qdrantRequest(
        `http://127.0.0.1:${address.port}`,
        "/stalled",
        {},
        50,
      )).rejects.toThrow("test Qdrant request timed out");
      expect(Date.now() - startedAt).toBeLessThan(500);
      await closeWithin(startClose, 500);
      expect(server.listening).toBe(false);
      const connections = await new Promise<number>((resolve, reject) => {
        server.getConnections((error, count) => error === null ? resolve(count) : reject(error));
      });
      expect(connections).toBe(0);
    } finally {
      clearTimeout(forcedCleanup);
      const pendingClose = startClose();
      server.closeAllConnections();
      await closeWithin(() => pendingClose, 500);
    }
  }, 2_000);
});

interface QdrantEnvelope {
  result?: unknown;
  status?: string;
}

interface RawQdrantResponse {
  status: number;
  ok: boolean;
  body: Uint8Array;
}

const RAW_QDRANT_REQUEST_TIMEOUT_MS = 1_000;

async function qdrantRequest(
  baseUrl: string,
  path: string,
  init: RequestInit = {},
  timeoutMs = RAW_QDRANT_REQUEST_TIMEOUT_MS,
): Promise<RawQdrantResponse> {
  if (!Number.isSafeInteger(timeoutMs) || timeoutMs <= 0) {
    throw new Error("test Qdrant request timeout is invalid");
  }
  const controller = new AbortController();
  const callerSignal = init.signal ?? undefined;
  let callerAborted = callerSignal?.aborted ?? false;
  let timedOut = false;
  let timer: NodeJS.Timeout | undefined;
  const onCallerAbort = (): void => {
    callerAborted = true;
    if (timer !== undefined) clearTimeout(timer);
    controller.abort();
  };
  if (callerSignal !== undefined && !callerAborted) {
    callerSignal.addEventListener("abort", onCallerAbort, { once: true });
  } else if (callerAborted) {
    controller.abort();
  }
  if (!callerAborted) {
    timer = setTimeout(() => {
      timedOut = true;
      controller.abort();
    }, timeoutMs);
  }

  try {
    const response = await fetch(`${baseUrl.replace(/\/+$/, "")}${path}`, {
      ...init,
      signal: controller.signal,
    });
    const body = new Uint8Array(await response.arrayBuffer());
    return { status: response.status, ok: response.ok, body };
  } catch {
    if (timedOut) throw new Error("test Qdrant request timed out");
    if (callerAborted) throw new Error("test Qdrant request cancelled");
    throw new Error("test Qdrant request unavailable");
  } finally {
    if (timer !== undefined) clearTimeout(timer);
    callerSignal?.removeEventListener("abort", onCallerAbort);
  }
}

function qdrantJson(response: RawQdrantResponse): QdrantEnvelope {
  try {
    return JSON.parse(Buffer.from(response.body).toString("utf8")) as QdrantEnvelope;
  } catch {
    throw new Error("test Qdrant JSON response was malformed");
  }
}

async function waitForQdrant(baseUrl: string, collection: string, timeoutMs = 15_000): Promise<void> {
  assertGeneratedCollection(collection);
  const client = new ReadonlyQdrantClient({ baseUrl, collection, timeoutMs: 500 });
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      await client.health();
      return;
    } catch {
      // The bounded readiness poll reports one stable error below.
    }
    await delay(Math.min(100, Math.max(1, deadline - Date.now())));
  }
  throw new Error("Qdrant did not become ready before the integration-test deadline");
}

async function collectionStatus(baseUrl: string, collection: string): Promise<number> {
  assertGeneratedCollection(collection);
  const response = await qdrantRequest(baseUrl, `/collections/${encodeURIComponent(collection)}`);
  return response.status;
}

async function waitForCollectionStatus(
  baseUrl: string,
  collection: string,
  expectedStatus: number,
  timeoutMs = 10_000,
): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  let status: number | undefined;
  while (Date.now() < deadline) {
    try {
      status = await collectionStatus(baseUrl, collection);
      if (status === expectedStatus) return;
    } catch {
      status = undefined;
    }
    await delay(Math.min(75, Math.max(1, deadline - Date.now())));
  }
  throw new Error(`collection ${collection} did not reach HTTP ${expectedStatus} (last ${status ?? "network-error"})`);
}

async function exactCount(baseUrl: string, collection: string): Promise<number> {
  assertGeneratedCollection(collection);
  const response = await qdrantRequest(baseUrl, `/collections/${encodeURIComponent(collection)}/points/count`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ exact: true }),
  });
  if (!response.ok) throw new Error(`Qdrant exact count failed with HTTP ${response.status}`);
  const body = qdrantJson(response);
  const result = body.result;
  if (typeof result !== "object" || result === null || !("count" in result)) {
    throw new Error("Qdrant exact count response was malformed");
  }
  const count = (result as { count?: unknown }).count;
  if (typeof count !== "number" || !Number.isSafeInteger(count) || count < 0) {
    throw new Error("Qdrant exact count response was malformed");
  }
  return count;
}

async function waitForExactCount(
  baseUrl: string,
  collection: string,
  expected: number,
  timeoutMs = 10_000,
): Promise<number> {
  const deadline = Date.now() + timeoutMs;
  let count: number | undefined;
  while (Date.now() < deadline) {
    count = await exactCount(baseUrl, collection);
    if (count === expected) return count;
    await delay(Math.min(75, Math.max(1, deadline - Date.now())));
  }
  throw new Error(`collection ${collection} did not reach exact count ${expected} (last ${count ?? "unknown"})`);
}

async function deleteGeneratedCollection(baseUrl: string, collection: string): Promise<void> {
  assertGeneratedCollection(collection);
  const response = await qdrantRequest(baseUrl, `/collections/${encodeURIComponent(collection)}`, { method: "DELETE" });
  if (response.status !== 404 && !response.ok) {
    throw new Error(`test collection cleanup failed with HTTP ${response.status}`);
  }
}

async function allPoints(client: AdminQdrantClient, collection: string): Promise<AdminPoint[]> {
  assertGeneratedCollection(collection);
  const points: AdminPoint[] = [];
  const seen = new Set<string>();
  let offset: string | number | undefined;
  while (true) {
    const page = await client.scroll(collection, offset, 256);
    points.push(...page.points);
    if (page.nextOffset === undefined) break;
    const key = `${typeof page.nextOffset}:${String(page.nextOffset)}`;
    if (seen.has(key)) throw new Error("unexpected repeated integration-test scroll offset");
    seen.add(key);
    offset = page.nextOffset;
  }
  return points.sort((left, right) => String(left.id).localeCompare(String(right.id)));
}

function payloadProjection(points: readonly AdminPoint[]): Array<{ id: string | number; payload: Record<string, unknown> }> {
  return points.map(point => ({ id: point.id, payload: structuredClone(point.payload) }));
}

function pointById(points: readonly AdminPoint[], id: string): AdminPoint {
  const point = points.find(candidate => candidate.id === id);
  if (point === undefined) throw new Error(`missing synthetic point ${id}`);
  return point;
}

function configuredIntegrationUrl(raw: string | undefined): string | undefined {
  if (raw === undefined) return undefined;
  const normalized = raw.trim().replace(/\/+$/, "");
  if (normalized.length === 0) {
    throw new Error("PI_QDRANT_MEMORY_TEST_QDRANT_URL is set but empty");
  }
  return normalized;
}

describe("integration environment gate", () => {
  it("distinguishes an absent URL from a present value that normalizes to empty", () => {
    const generatedBefore = generatedCollections.size;
    expect(configuredIntegrationUrl(undefined)).toBeUndefined();
    expect(() => configuredIntegrationUrl("   ///   "))
      .toThrow("PI_QDRANT_MEMORY_TEST_QDRANT_URL is set but empty");
    expect(generatedCollections.size).toBe(generatedBefore);
  });
});

const configuredQdrantUrl = configuredIntegrationUrl(process.env.PI_QDRANT_MEMORY_TEST_QDRANT_URL);

describe("real Qdrant runtime and approved import integration", () => {
  if (configuredQdrantUrl === undefined) {
    it.skip("PI_QDRANT_MEMORY_TEST_QDRANT_URL is not set", () => {});
    return;
  }

  const qdrantUrl = configuredQdrantUrl;
  const sourceCollection = generatedCollection(SOURCE_PREFIX);
  const destinationCollection = generatedCollection(DESTINATION_PREFIX);
  const integrationModel = "pi-qdrant-memory-integration-model";
  const dimension = 4;
  let sourceAdmin: AdminQdrantClient;
  let destinationAdmin: AdminQdrantClient;
  let embeddingStub: Awaited<ReturnType<typeof startEmbeddingStub>> | undefined;

  beforeAll(async () => {
    await waitForQdrant(qdrantUrl, sourceCollection);
    sourceAdmin = new AdminQdrantClient({ baseUrl: qdrantUrl, timeoutMs: 5_000 });
    destinationAdmin = new AdminQdrantClient({ baseUrl: qdrantUrl, timeoutMs: 5_000 });
    embeddingStub = await startEmbeddingStub();
    await sourceAdmin.createCollection(sourceCollection, dimension, "Cosine");
    await destinationAdmin.createCollection(destinationCollection, dimension, "Cosine");
    for (const field of ["host", "project_id", "status", "secret_scan", "source_type"]) {
      await destinationAdmin.createKeywordIndex(destinationCollection, field);
    }
    await waitForCollectionStatus(qdrantUrl, sourceCollection, 200);
    await waitForCollectionStatus(qdrantUrl, destinationCollection, 200);
  }, 30_000);

  afterAll(async () => {
    const errors: unknown[] = [];
    if (embeddingStub !== undefined) {
      try {
        await closeWithin(embeddingStub.close);
      } catch (error: unknown) {
        errors.push(error);
      }
    }
    for (const collection of [sourceCollection, destinationCollection]) {
      try {
        await deleteGeneratedCollection(qdrantUrl, collection);
        await waitForCollectionStatus(qdrantUrl, collection, 404);
        console.info(`cleanup verified HTTP 404: ${collection}`);
      } catch (error: unknown) {
        errors.push(error);
      }
    }
    if (errors.length > 0) throw new AggregateError(errors, "integration cleanup failed");
  }, 30_000);

  it("uses product clients/retrieval/import interfaces without mutating source payloads", async () => {
    if (embeddingStub === undefined) throw new Error("embedding stub was not started");
    const embeddings = new EmbeddingsClient({
      baseUrl: embeddingStub.baseUrl,
      model: integrationModel,
      dimension,
      queryPrefix: "search_query: ",
      timeoutMs: 5_000,
    });
    const query = "synthetic integration query";
    const queryVector = await embeddings.embedQuery(query);
    expect(queryVector).toEqual(expectedEmbedding(integrationModel, `search_query: ${query}`));

    const currentProjectId = "synthetic-current-project";
    const runtimeIds = {
      current: "10000000-0000-4000-8000-000000000001",
      globalA: "10000000-0000-4000-8000-000000000002",
      globalB: "10000000-0000-4000-8000-000000000003",
      other: "10000000-0000-4000-8000-000000000004",
      pi: "10000000-0000-4000-8000-000000000005",
      blocked: "10000000-0000-4000-8000-000000000006",
      failedScan: "10000000-0000-4000-8000-000000000007",
      missingScan: "10000000-0000-4000-8000-000000000008",
    } as const;
    const runtimePayload = (text: string, extra: Record<string, unknown> = {}): Record<string, unknown> => ({
      text,
      host: "prime",
      status: "active",
      secret_scan: "passed",
      source_type: "synthetic",
      source_system: "integration-test",
      ...extra,
    });
    const runtimePoints: AdminPoint[] = [
      { id: runtimeIds.failedScan, vector: queryVector, payload: runtimePayload("failed scan", { project_id: currentProjectId, secret_scan: "failed" }) },
      { id: runtimeIds.other, vector: queryVector, payload: runtimePayload("other project", { project_id: "synthetic-other-project", project_label: "other" }) },
      { id: runtimeIds.globalB, vector: queryVector, payload: runtimePayload("global beta") },
      { id: runtimeIds.pi, vector: queryVector, payload: runtimePayload("wrong host", { host: "pi" }) },
      { id: runtimeIds.current, vector: queryVector, payload: runtimePayload("current project", { project_id: currentProjectId, project_label: "current" }) },
      {
        id: runtimeIds.missingScan,
        vector: queryVector,
        payload: {
          text: "missing scan",
          host: "prime",
          status: "active",
          source_type: "synthetic",
          source_system: "integration-test",
          project_id: currentProjectId,
        },
      },
      { id: runtimeIds.globalA, vector: queryVector, payload: runtimePayload("global alpha") },
      { id: runtimeIds.blocked, vector: queryVector, payload: runtimePayload("blocked", { project_id: currentProjectId, status: "blocked" }) },
    ];
    await destinationAdmin.upsert(destinationCollection, runtimePoints);
    expect(await waitForExactCount(qdrantUrl, destinationCollection, runtimePoints.length)).toBe(runtimePoints.length);

    const retrievalConfig: RetrievalConfig = {
      topK: 10,
      candidatesPerLane: 20,
      minScore: 0.99,
      projectBoost: 0.05,
      contextBudgetChars: 1200,
      toolResultBudgetChars: 8000,
      hardContextCharBudget: 16000,
      timeoutMs: 5_000,
    };
    const readonlyQdrant = new ReadonlyQdrantClient({
      baseUrl: qdrantUrl,
      collection: destinationCollection,
      timeoutMs: 5_000,
    });
    await expect(readonlyQdrant.health()).resolves.toBeUndefined();
    await expect(readonlyQdrant.collectionInfo()).resolves.toEqual({ dimension, distance: "Cosine" });
    const retriever = new MemoryRetriever({ embeddings, qdrant: readonlyQdrant, config: retrievalConfig });
    const search = await retriever.search({
      query,
      host: "prime",
      project: { id: currentProjectId, label: "current" },
      limit: 10,
    });
    expect(search.hits.map(hit => hit.id)).toEqual([
      runtimeIds.current,
      runtimeIds.globalA,
      runtimeIds.globalB,
      runtimeIds.other,
    ]);
    expect(search.hits[0]).toMatchObject({ id: runtimeIds.current, lane: "project" });
    expect(search.hits.slice(1).every(hit => hit.lane === "host")).toBe(true);
    expect(search.hits[0]?.rawScore).toBeCloseTo(search.hits[1]?.rawScore ?? 0, 6);
    expect(search.hits[0]?.adjustedScore).toBeGreaterThan(search.hits[1]?.adjustedScore ?? Number.POSITIVE_INFINITY);
    expect(search.hits.slice(1).map(hit => hit.id)).toEqual([
      runtimeIds.globalA,
      runtimeIds.globalB,
      runtimeIds.other,
    ]);
    for (const hit of search.hits) {
      const fixture = pointById(runtimePoints, hit.id);
      expect(fixture.payload).toMatchObject({ host: "prime", status: "active", secret_scan: "passed" });
    }
    for (const excluded of [runtimeIds.pi, runtimeIds.blocked, runtimeIds.failedScan, runtimeIds.missingScan]) {
      expect(search.hits.map(hit => hit.id)).not.toContain(excluded);
    }
    expect(embeddingStub.requests).toHaveLength(2);
    expect(embeddingStub.requests.every(request => Object.isFrozen(request))).toBe(true);
    expect(embeddingStub.requests).toEqual([
      expect.objectContaining({ method: "POST", contentType: "application/json", model: integrationModel, input: `search_query: ${query}` }),
      expect.objectContaining({ method: "POST", contentType: "application/json", model: integrationModel, input: `search_query: ${query}` }),
    ]);

    const sourceProjectPath = `/synthetic/pi-qdrant-memory/${sourceCollection}/project-alpha`;
    const sourceIds = {
      project: "20000000-0000-4000-8000-000000000001",
      global: "20000000-0000-4000-8000-000000000002",
      blocked: "20000000-0000-4000-8000-000000000003",
    } as const;
    const sourcePoints: AdminPoint[] = [
      {
        id: sourceIds.project,
        vector: [0.5, 0.5, 0.5, 0.5],
        payload: {
          text: "synthetic imported project memory",
          model: integrationModel,
          project_path: sourceProjectPath,
          source_type: "conversation",
          created_at: "2026-08-08T10:11:12Z",
          tags: ["synthetic", "integration"],
          fact_status: "active",
          stale: false,
        },
      },
      {
        id: sourceIds.global,
        vector: [-0.5, 0.5, -0.5, 0.5],
        payload: { text: "synthetic imported global memory", model: integrationModel },
      },
      {
        id: sourceIds.blocked,
        vector: [0.5, -0.5, 0.5, -0.5],
        payload: { text: "synthetic rejected source memory", model: integrationModel, fact_status: "blocked" },
      },
    ];
    await sourceAdmin.upsert(sourceCollection, sourcePoints);
    expect(await waitForExactCount(qdrantUrl, sourceCollection, sourcePoints.length)).toBe(sourcePoints.length);

    const sourceBefore = await allPoints(sourceAdmin, sourceCollection);
    const sourceCountBefore = await exactCount(qdrantUrl, sourceCollection);
    const sourcePayloadBefore = payloadProjection(sourceBefore);
    const destinationCountBeforeDryRun = await exactCount(qdrantUrl, destinationCollection);
    const importOptions: ImportOptions = {
      sourceIdentity: qdrantUrl,
      sourceCollection,
      destinationCollection,
      targetHost: "prime",
      configuredModel: integrationModel,
      configuredDimension: dimension,
    };
    const importClients = { source: sourceAdmin, destination: destinationAdmin };

    const dryRun = await planHermesImport(importOptions, importClients);
    expect(dryRun.planId).toMatch(/^[a-f0-9]{64}$/);
    expect(dryRun.report).toEqual({
      accepted: 2,
      rejected: 1,
      bySourceType: { conversation: 1, unknown: 1 },
      byProjectLabel: { global: 1, "project-alpha": 1 },
    });
    expect(dryRun.rejected).toEqual({ "fact-status": 1 });
    expect(await exactCount(qdrantUrl, destinationCollection)).toBe(destinationCountBeforeDryRun);

    const firstApply = await applyHermesImport({ ...importOptions, approvedPlanId: dryRun.planId }, importClients);
    expect(firstApply).toEqual({ planId: dryRun.planId, upserted: 2, batches: 1 });
    const destinationCountAfterApply = destinationCountBeforeDryRun + dryRun.report.accepted;
    expect(await waitForExactCount(qdrantUrl, destinationCollection, destinationCountAfterApply)).toBe(destinationCountAfterApply);

    const importedAfterFirstApply = (await allPoints(destinationAdmin, destinationCollection))
      .filter(point => point.payload.source_collection === sourceCollection)
      .sort((left, right) => String(left.payload.source_point_id).localeCompare(String(right.payload.source_point_id)));
    const expectedProjectId = createHash("sha256").update(sourceProjectPath).digest("hex");
    expect(importedAfterFirstApply).toHaveLength(2);
    expect(importedAfterFirstApply.map(point => point.payload)).toEqual([
      {
        text: "synthetic imported project memory",
        host: "prime",
        project_id: expectedProjectId,
        project_label: "project-alpha",
        source_type: "conversation",
        source_system: "hermes",
        source_collection: sourceCollection,
        source_point_id: sourceIds.project,
        created_at: "2026-08-08T10:11:12Z",
        tags: ["synthetic", "integration"],
        status: "active",
        secret_scan: "passed",
        import_run_id: dryRun.planId,
      },
      {
        text: "synthetic imported global memory",
        host: "prime",
        source_type: "unknown",
        source_system: "hermes",
        source_collection: sourceCollection,
        source_point_id: sourceIds.global,
        status: "active",
        secret_scan: "passed",
        import_run_id: dryRun.planId,
      },
    ]);
    expect(importedAfterFirstApply.every(point => !("model" in point.payload))).toBe(true);
    const stableIdsAndRuns = importedAfterFirstApply.map(point => ({
      id: point.id,
      importRunId: point.payload.import_run_id,
    }));
    expect(stableIdsAndRuns).toEqual(dryRun.accepted.map(point => ({
      id: point.id,
      importRunId: dryRun.planId,
    })));

    const secondApply = await applyHermesImport({ ...importOptions, approvedPlanId: dryRun.planId }, importClients);
    expect(secondApply).toEqual(firstApply);
    expect(await waitForExactCount(qdrantUrl, destinationCollection, destinationCountAfterApply)).toBe(destinationCountAfterApply);
    const importedAfterSecondApply = (await allPoints(destinationAdmin, destinationCollection))
      .filter(point => point.payload.source_collection === sourceCollection)
      .sort((left, right) => String(left.payload.source_point_id).localeCompare(String(right.payload.source_point_id)));
    expect(importedAfterSecondApply.map(point => ({ id: point.id, importRunId: point.payload.import_run_id })))
      .toEqual(stableIdsAndRuns);
    expect(importedAfterSecondApply).toEqual(importedAfterFirstApply);

    const sourceAfterProductOperations = await allPoints(sourceAdmin, sourceCollection);
    expect(await exactCount(qdrantUrl, sourceCollection)).toBe(sourceCountBefore);
    expect(sourceAfterProductOperations).toEqual(sourceBefore);

    const mutatedSource = pointById(sourceAfterProductOperations, sourceIds.project);
    await sourceAdmin.upsert(sourceCollection, [{
      id: mutatedSource.id,
      vector: [0.25, 0.5, 0.75, 1],
      payload: structuredClone(mutatedSource.payload),
    }]);
    expect(await waitForExactCount(qdrantUrl, sourceCollection, sourceCountBefore)).toBe(sourceCountBefore);
    const sourceAfterOwnedMutation = await allPoints(sourceAdmin, sourceCollection);
    expect(payloadProjection(sourceAfterOwnedMutation)).toEqual(sourcePayloadBefore);
    expect(pointById(sourceAfterOwnedMutation, sourceIds.project).vector)
      .not.toEqual(pointById(sourceBefore, sourceIds.project).vector);
    for (const id of [sourceIds.global, sourceIds.blocked]) {
      expect(pointById(sourceAfterOwnedMutation, id).vector).toEqual(pointById(sourceBefore, id).vector);
    }

    const destinationBeforeMismatch = await allPoints(destinationAdmin, destinationCollection);
    const destinationCountBeforeMismatch = await exactCount(qdrantUrl, destinationCollection);
    const destinationUpsert = vi.spyOn(destinationAdmin, "upsert");
    let mismatch: unknown;
    try {
      await applyHermesImport({ ...importOptions, approvedPlanId: dryRun.planId }, importClients);
    } catch (error: unknown) {
      mismatch = error;
    }
    expect(mismatch).toBeInstanceOf(Error);
    expect((mismatch as Error).message).toBe("source changed; run dry-run again");
    expect(destinationUpsert).not.toHaveBeenCalled();
    destinationUpsert.mockRestore();
    expect(await exactCount(qdrantUrl, destinationCollection)).toBe(destinationCountBeforeMismatch);
    expect(await allPoints(destinationAdmin, destinationCollection)).toEqual(destinationBeforeMismatch);
    expect(await exactCount(qdrantUrl, sourceCollection)).toBe(sourceCountBefore);
    const sourceAfterRejectedApply = await allPoints(sourceAdmin, sourceCollection);
    expect(payloadProjection(sourceAfterRejectedApply)).toEqual(sourcePayloadBefore);
    expect(sourceAfterRejectedApply).toEqual(sourceAfterOwnedMutation);

    console.info(`integration collections: source=${sourceCollection} destination=${destinationCollection}`);
  }, 45_000);
});
